"""The Standard Model kernel K_l(b), reimplemented in Python.

Mirrors SMI.RotInv_Kell_wFW_b_beta_TE_numerical (SMI.m:2033) for LTE, single
TE. Used only to build the CSD / MSMT-CSD response functions; the DWI signal
itself is always generated by SMI's own Octave code, so this file can never
put the two pipelines on different data.

Verified against the Octave original to ~1e-12 by check_kernel.py.
"""
import numpy as np
from numpy.polynomial.legendre import leggauss

# Legendre polynomials in x, matching SMI.m:2099-2107
_P = {
    0: lambda x: np.ones_like(x),
    2: lambda x: 1.5 * x**2 - 0.5,
    4: lambda x: (35 * x**4 - 30 * x**2 + 3) / 8,
    6: lambda x: (231 * x**6 - 315 * x**4 + 105 * x**2 - 5) / 16,
    8: lambda x: (6435 * x**8 - 12012 * x**6 + 6930 * x**4
                  - 1260 * x**2 + 35) / 128,
}


def Kell(ell, b, kernel, D_FW=3.0, n=200):
    """K_l(b) for kernel = [f, Da, Depar, Deperp, fw], b in ms/um^2.

    Exactly SMI.m:2110-2113 for LTE (beta=1), single TE:

      K_l(b) = int_0^1 [ f e^{-b Da x^2}
                       + (1-f-fw) e^{-b(Deperp + Delta_e x^2)}
                       + fw e^{-b D_FW} ] P_l(x) dx

    Note there is NO (2l+1) prefactor, and the free water term is carried for
    every l -- int_0^1 P_l dx = 0 for even l >= 2 removes it automatically, so
    it only survives at l=0.
    """
    f, Da, Depar, Deperp, fw = kernel
    b = np.atleast_1d(np.asarray(b, dtype=float))
    # 200-point Gauss-Legendre mapped to [0,1]; weights sum to 1
    x, w = leggauss(n)
    x = 0.5 * (x + 1.0)
    w = 0.5 * w
    P = _P[ell](x)
    dpar = Depar - Deperp
    integ = (f * np.exp(-np.outer(b, Da * x**2))
             + (1 - f - fw) * np.exp(-np.outer(b, Deperp + dpar * x**2))
             + fw * np.exp(-np.outer(b, D_FW * np.ones_like(x))))
    out = (integ * (w * P)).sum(axis=1)
    if ell > 0:
        out = np.where(b < 1e-6, 0.0, out)      # SMI.m:2117
    return out


def response_sh(b, kernel, lmax, D_FW=3.0):
    """Axially symmetric SH coefficients (m=0) of the single-fibre response.

    For a delta fODF the normalised p_l0 are all 1, so
        R(theta) = sum_l (2l+1) K_l(b) P_l(cos theta)
    and matching R = sum_l r_l Y_l0 with Y_l0 = sqrt((2l+1)/4pi) P_l gives
        r_l = K_l(b) * sqrt((2l+1) * 4pi)
    which is exactly the N_l factor SMI uses (SMI.m:724).
    """
    ls = np.arange(0, lmax + 1, 2)
    return np.array([Kell(l, b, kernel, D_FW)[0] * np.sqrt((2 * l + 1) * 4 * np.pi)
                     for l in ls])
